# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFX_config = debug

else ifeq ($(config),release)
  GLFX_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFX

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GLFX:
ifneq (,$(GLFX_config))
	@echo "==== Building GLFX ($(GLFX_config)) ===="
	@${MAKE} --no-print-directory -C . -f GLFX.make config=$(GLFX_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f GLFX.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFX"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"